# Generated by Django 4.1.1 on 2023-01-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_options_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
    ]
